// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.example.demo.nano;

@SuppressWarnings("hiding")
public interface Training {

  public static final class Course extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Course[] _emptyArray;
    public static Course[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Course[0];
          }
        }
      }
      return _emptyArray;
    }

    // int32 id = 1;
    public int id;

    // string course_name = 2;
    public java.lang.String courseName;

    // repeated .demo.Student student = 3;
    public com.example.demo.nano.Training.Student[] student;

    public Course() {
      clear();
    }

    public Course clear() {
      id = 0;
      courseName = "";
      student = com.example.demo.nano.Training.Student.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.id != 0) {
        output.writeInt32(1, this.id);
      }
      if (!this.courseName.equals("")) {
        output.writeString(2, this.courseName);
      }
      if (this.student != null && this.student.length > 0) {
        for (int i = 0; i < this.student.length; i++) {
          com.example.demo.nano.Training.Student element = this.student[i];
          if (element != null) {
            output.writeMessage(3, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.id != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.id);
      }
      if (!this.courseName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.courseName);
      }
      if (this.student != null && this.student.length > 0) {
        for (int i = 0; i < this.student.length; i++) {
          com.example.demo.nano.Training.Student element = this.student[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(3, element);
          }
        }
      }
      return size;
    }

    @Override
    public Course mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.id = input.readInt32();
            break;
          }
          case 18: {
            this.courseName = input.readString();
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.student == null ? 0 : this.student.length;
            com.example.demo.nano.Training.Student[] newArray =
                new com.example.demo.nano.Training.Student[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.student, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.example.demo.nano.Training.Student();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.example.demo.nano.Training.Student();
            input.readMessage(newArray[i]);
            this.student = newArray;
            break;
          }
        }
      }
    }

    public static Course parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Course(), data);
    }

    public static Course parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Course().mergeFrom(input);
    }
  }

  public static final class Student extends
      com.google.protobuf.nano.MessageNano {

    // enum PhoneType
    public static final int MOBILE = 0;
    public static final int LANDLINE = 1;

    public static final class PhoneNumber extends
        com.google.protobuf.nano.MessageNano {

      private static volatile PhoneNumber[] _emptyArray;
      public static PhoneNumber[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new PhoneNumber[0];
            }
          }
        }
        return _emptyArray;
      }

      // string number = 1;
      public java.lang.String number;

      // .demo.Student.PhoneType type = 2;
      public int type;

      public PhoneNumber() {
        clear();
      }

      public PhoneNumber clear() {
        number = "";
        type = com.example.demo.nano.Training.Student.MOBILE;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!this.number.equals("")) {
          output.writeString(1, this.number);
        }
        if (this.type != com.example.demo.nano.Training.Student.MOBILE) {
          output.writeInt32(2, this.type);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!this.number.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, this.number);
        }
        if (this.type != com.example.demo.nano.Training.Student.MOBILE) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.type);
        }
        return size;
      }

      @Override
      public PhoneNumber mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.number = input.readString();
              break;
            }
            case 16: {
              int value = input.readInt32();
              switch (value) {
                case com.example.demo.nano.Training.Student.MOBILE:
                case com.example.demo.nano.Training.Student.LANDLINE:
                  this.type = value;
                  break;
              }
              break;
            }
          }
        }
      }

      public static PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new PhoneNumber(), data);
      }

      public static PhoneNumber parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new PhoneNumber().mergeFrom(input);
      }
    }

    private static volatile Student[] _emptyArray;
    public static Student[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Student[0];
          }
        }
      }
      return _emptyArray;
    }

    // int32 id = 1;
    public int id;

    // string first_name = 2;
    public java.lang.String firstName;

    // string last_name = 3;
    public java.lang.String lastName;

    // string email = 4;
    public java.lang.String email;

    // repeated .demo.Student.PhoneNumber phone = 5;
    public com.example.demo.nano.Training.Student.PhoneNumber[] phone;

    public Student() {
      clear();
    }

    public Student clear() {
      id = 0;
      firstName = "";
      lastName = "";
      email = "";
      phone = com.example.demo.nano.Training.Student.PhoneNumber.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.id != 0) {
        output.writeInt32(1, this.id);
      }
      if (!this.firstName.equals("")) {
        output.writeString(2, this.firstName);
      }
      if (!this.lastName.equals("")) {
        output.writeString(3, this.lastName);
      }
      if (!this.email.equals("")) {
        output.writeString(4, this.email);
      }
      if (this.phone != null && this.phone.length > 0) {
        for (int i = 0; i < this.phone.length; i++) {
          com.example.demo.nano.Training.Student.PhoneNumber element = this.phone[i];
          if (element != null) {
            output.writeMessage(5, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.id != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.id);
      }
      if (!this.firstName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.firstName);
      }
      if (!this.lastName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.lastName);
      }
      if (!this.email.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.email);
      }
      if (this.phone != null && this.phone.length > 0) {
        for (int i = 0; i < this.phone.length; i++) {
          com.example.demo.nano.Training.Student.PhoneNumber element = this.phone[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(5, element);
          }
        }
      }
      return size;
    }

    @Override
    public Student mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.id = input.readInt32();
            break;
          }
          case 18: {
            this.firstName = input.readString();
            break;
          }
          case 26: {
            this.lastName = input.readString();
            break;
          }
          case 34: {
            this.email = input.readString();
            break;
          }
          case 42: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 42);
            int i = this.phone == null ? 0 : this.phone.length;
            com.example.demo.nano.Training.Student.PhoneNumber[] newArray =
                new com.example.demo.nano.Training.Student.PhoneNumber[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.phone, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.example.demo.nano.Training.Student.PhoneNumber();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.example.demo.nano.Training.Student.PhoneNumber();
            input.readMessage(newArray[i]);
            this.phone = newArray;
            break;
          }
        }
      }
    }

    public static Student parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Student(), data);
    }

    public static Student parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Student().mergeFrom(input);
    }
  }
}
